export const videoSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    category_id: { type: 'string' },
    title: { type: 'string' },
    trailer: { type: 'string', format: 'uri' },
    thumbnil: { type: 'string', format: 'uri' },
    video_url: { type: 'string', format: 'uri' },
    bg_url: { type: 'string', format: 'uri' },
    description: { type: 'string' },
    director_name: { type: 'string' },
    actor_name: { type: 'string' },
    release_year: { type: 'string' },
    video_type: { type: 'string' },
    partial_guide: { type: 'string' },
    is_public: { type: 'boolean' },
  },
  required: [
    'category_id',
    'title',
    'trailer',
    'thumbnil',
    'bg_url',
    'video_url',
    'description',
    'director_name',
    'actor_name',
    'release_year',
    'video_type',
    'partial_guide',
    'is_public',
  ],
};
export const videoUpdaateSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    category_id: { type: 'string' },
    title: { type: 'string' },
    trailer: { type: 'string', format: 'uri' },
    thumbnil: { type: 'string', format: 'uri' },
    video_url: { type: 'string', format: 'uri' },
    bg_url: { type: 'string', format: 'uri' },
    description: { type: 'string' },
    director_name: { type: 'string' },
    actor_name: { type: 'string' },
    release_year: { type: 'string' },
    video_type: { type: 'string' },
    partial_guide: { type: 'string' },
    is_public: { type: 'boolean' },
  },
};
